config/routes.rb
Rails.application.routes.draw do
  resources :orders, except: [:show]

  resources :users

  resources :photobooks

  get 'orders/create' => "orders#create", as: :new_orders_url
  get 'orders/display' => "orders#show", as: :display_orders_url
  get 'orders/express_checkout' => "orders#express_checkout", as: :express_checkout_path
  get 'static/home'

  get 'static/welcome'

  get 'static/privacy'

  get 'static/about_us'

  get 'static/blog'

  root 'users#edit'

end

app/models/order.rb
class Order
  include Mongoid::Document
  field :id, type: String
  field :shipping_address, type: String
  field :payment_method, type: String
  field :raw, type: String
  field :total_amount, type: String
  field :express_token, type: String
  field :ip, type: String
  field :express_payer_id, type: String
  field :purchased_at, type: Time

  belongs_to :user, inverse_of: :order
  has_many :photobooks, inverse_of: :order, :autosave => true

  def purchase
    response = EXPRESS_GATEWAY.purchase(100, express_purchase_options)
    #cart.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end
  def express_purchase_options
    {
        :ip => ip,
        :token => express_token,
        :payer_id => express_payer_id
    }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :display]

  def express_checkout
    Rails.logger.info "*********** Params"
    Rails.logger.info params.inspect
    response = EXPRESS_GATEWAY.setup_purchase(100,
                                              ip: request.remote_ip,
                                              return_url: "https://app.momentleaf.com/orders/create",
                                              cancel_return_url: "https://app.momentleaf.com",
                                              currency: "USD",
                                              allow_guest_checkout: true,
                                              items: [{name: "Moment leaf photobook", description: "Collection of # of photos", quantity: "1", amount: 100}]
    )
    Rails.logger.info response.inspect
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show

  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new #(order_params)
    @order.total_amount = "100"
    @order.payment_method = "PAYPAL"
    @order.express_token = params[:token]
    @order.express_payer_id = params[:PayerID]
    @order.ip = request.remote_ip

    #TODO change user and photobook with current user and params of photobook
    @order.photobooks = [Photobook.first]
    @order.user      = User.first

    respond_to do |format|
      if @order.purchase
        @order.save!
        format.html { redirect_to "https://app.momentleaf.com/orders/display?id=#{@order.id}", notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:id, :shipping_address, :payment_method, :raw, :token)
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :shipping_address %><br>
    <%= f.text_field :shipping_address %>
  </div>
  <div class="field">
    <%= f.label :payment_method %><br>
    <%= f.text_field :payment_method %>
  </div>
  <div class="field">
    <%= f.label :raw %><br>
    <%= f.text_field :raw %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Shipping address</th>
      <th>Payment method</th>
      <th>Raw</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.shipping_address %></td>
        <td><%= order.payment_method %></td>
        <td><%= order.raw %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @order.id %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @order.payment_method %>
</p>

<p>
  <strong>Raw:</strong>
  <%= @order.raw %>
</p>

<%= @order.to_json %>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>