config/routes.rb
Rails.application.routes.draw do
  resources :orders, except: [:show]

  resources :users

  resources :photobooks

  get 'orders/create' => "orders#create", as: :new_orders_url
  get 'orders/display' => "orders#show", as: :display_orders_url
  get 'orders/express_checkout' => "orders#express_checkout", as: :express_checkout_path
  get 'static/home'

  get 'static/welcome'

  get 'static/privacy'

  get 'static/about_us'

  get 'static/blog'

  root 'users#edit'

end

app/models/photobook.rb
class Photobook
  include Mongoid::Document
  field :id, type: String
  field :name, type: String
  field :photos, type: Array

  belongs_to :user, inverse_of: :photobook
  belongs_to :order, inverse_of: :photobook
end

app/controllers/photobooks_controller.rb
class PhotobooksController < ApplicationController
  before_action :set_photobook, only: [:show, :edit, :update, :destroy]

  # GET /photobooks
  # GET /photobooks.json
  def index
    @photobooks = Photobook.all
  end

  # GET /photobooks/1
  # GET /photobooks/1.json
  def show
  end

  # GET /photobooks/new
  def new
    @photobook = Photobook.new
  end

  # GET /photobooks/1/edit
  def edit
  end

  # POST /photobooks
  # POST /photobooks.json
  def create
    @photobook = Photobook.new(photobook_params)
    #TODO replace with current user
    @photobook.user = User.first
    respond_to do |format|
      if @photobook.save
        format.html { redirect_to @photobook, notice: 'Photobook was successfully created.' }
        format.json { render :show, status: :created, location: @photobook }
      else
        format.html { render :new }
        format.json { render json: @photobook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photobooks/1
  # PATCH/PUT /photobooks/1.json
  def update
    respond_to do |format|
      if @photobook.update(photobook_params)
        format.html { redirect_to @photobook, notice: 'Photobook was successfully updated.' }
        format.json { render :show, status: :ok, location: @photobook }
      else
        format.html { render :edit }
        format.json { render json: @photobook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photobooks/1
  # DELETE /photobooks/1.json
  def destroy
    @photobook.destroy
    respond_to do |format|
      format.html { redirect_to photobooks_url, notice: 'Photobook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photobook
      @photobook = Photobook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photobook_params
      params.require(:photobook).permit(:id, :name, {:photos => []})
    end
end

app/helpers/photobooks_helper.rb
module PhotobooksHelper
end

app/views/photobooks/_form.html.erb
<%= form_for(@photobook) do |f| %>
  <% if @photobook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photobook.errors.count, "error") %> prohibited this photobook from being saved:</h2>

      <ul>
      <% @photobook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photos %><br>
    <%= f.text_field :photos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photobooks/edit.html.erb
<h1>Editing Photobook</h1>

<%= render 'form' %>

<%= link_to 'Show', @photobook %> |
<%= link_to 'Back', photobooks_path %>

app/views/photobooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photobooks</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Photos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photobooks.each do |photobook| %>
      <tr>
        <td><%= photobook.id %></td>
        <td><%= photobook.name %></td>
        <td><%= photobook.photos %></td>
        <td><%= link_to 'Show', photobook %></td>
        <td><%= link_to 'Edit', edit_photobook_path(photobook) %></td>
        <td><%= link_to 'Destroy', photobook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photobook', new_photobook_path %>

app/views/photobooks/new.html.erb
<h1>New Photobook</h1>

<%= render 'form' %>

<%= link_to 'Back', photobooks_path %>

app/views/photobooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @photobook.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @photobook.name %>
</p>

<p>
  <strong>Photos:</strong>
  <%= @photobook.photos %>
</p>

<%= link_to 'Edit', edit_photobook_path(@photobook) %> |
<%= link_to 'Back', photobooks_path %>